### ISSUE TITLE
conntrack-tools issue

### ISSUE THREAD

**Issue by colebrumley** [EricR/sys.json#10]
What version of conntrack were you using for testing?  I just tried the conntrack module on a RHEL7 host and get errors:

```
[root@testrhn bin]# ./sysjson -listen 0.0.0.0:8080
2015/03/04 07:10:36 [notice] sys.json listening on 0.0.0.0:8080
2015/03/04 07:10:39 http: panic serving 10.12.134.32:9151: runtime error: index out of range
goroutine 20 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x68e180, 0x84351c)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/ericr/sysjson/src/plugins/conntrack.GetStats(0x60aea0)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/plugins/conntrack/conntrack.go:57 +0xa42
main.loadModules(0xc20800ec90, 0xc2080400ce, 0x9, 0x7)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/modules.go:81 +0x383
main.statsHandler(0x7fd50509fa78, 0xc2080520a0, 0xc208000000)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/sysjson.go:43 +0xc6
net/http.HandlerFunc.ServeHTTP(0x74a288, 0x7fd50509fa78, 0xc2080520a0, 0xc208000000)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc20800eba0, 0x7fd50509fa78, 0xc2080520a0, 0xc208000000)
        /usr/lib/golang/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080042a0, 0x7fd50509fa78, 0xc2080520a0, 0xc208000000)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208050280)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
2015/03/04 07:10:39 http: panic serving 10.12.134.32:9155: runtime error: index out of range
goroutine 21 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x68e180, 0x84351c)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/ericr/sysjson/src/plugins/conntrack.GetStats(0x60aea0)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/plugins/conntrack/conntrack.go:57 +0xa42
main.loadModules(0xc20800eff0, 0xc2080408ce, 0x9, 0x7)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/modules.go:81 +0x383
main.statsHandler(0x7fd50509fa78, 0xc2080523c0, 0xc208000270)
        /home/eric/code/go/src/github.com/ericr/sysjson/src/sysjson.go:43 +0xc6
net/http.HandlerFunc.ServeHTTP(0x74a288, 0x7fd50509fa78, 0xc2080523c0, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc20800eba0, 0x7fd50509fa78, 0xc2080523c0, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080042a0, 0x7fd50509fa78, 0xc2080523c0, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208050400)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
```

When I tried running the command used in the code it's saying:

```
[root@testrhn bin]# conntrack -L -f -o extend
conntrack v1.4.2 (conntrack-tools): `-o' unsupported protocol
Try `conntrack -h' or 'conntrack --help' for more information.
```

Took a quick look at the conntrack docs and it looks like the error (on my end at least) is that the -f flag is looking for a protocol (ipv4/ipv6).  I recompiled without the -f flag on conntrack and it's coming back fine.

~~Also, would it not be easier to use conntrack's XML output and then unmarshal it with encoding/xml?  I.e. `conntrack -L -o extend,xml`~~ Never mind, encoding/xml can't unmarshal the lower case fields that conntrack returns in its XML.

**Comment by EricR** [comment]
Ah, whoops, that -f flag shouldn't be there. I'll push a fix for this later.

Don't know how it ever worked for me. My version of conntrack doesn't like it either. Weird.
